# Generated by Django 3.2 on 2021-11-30 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geo_places', '0002_auto_20211126_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='address',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='название'),
        ),
    ]
