# Generated by Django 3.2 on 2021-11-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20211110_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Необработанный'), ('in process', 'Готовится'), ('done', 'Сделан'), ('canceled', 'Отменен')], default='waiting', max_length=20),
        ),
    ]
