# Generated by Django 3.2 on 2021-11-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='processed',
        ),
    ]
