# Generated by Django 3.2 on 2021-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_remove_order_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
