# Generated by Django 3.2 on 2021-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20211125_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('bank_card', 'Оплата картой'), ('not_set', 'Не указано')], db_index=True, default='not_set', max_length=20),
        ),
    ]
